### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xharky** [codeuk/TrollWare#2]
Its the same error

**Comment by codeuk** [comment]
What do you even mean by this? same error as what? If you're referring to the latest issue that I **closed** and have **mentioned** in the readme, where I also mentioned that I'm not maintaining this due to it's un-needed complexity, then go look at the readme where I say you can just remove functions with errors and change what they return.

Otherwise, leave an actual error here which you can just paste from your command-line.
Before you say it just closes:
- Open CMD in the directory you have TrollWare in.
- Run these commands:

      pip install -r requirements.txt
      python main.py

- When the error shows, come back to this issue and comment it for me to diagnose.

**Comment by codeuk** [comment]
As you've failed to respond, I'm going to assume you've either
- fixed the problem and have no need to respond, or;
- cannot be bothered continuing the thread

I'll now **close the issue** due to your inactivity, but if you face any more issues while following the steps in my last comment, please create another issue.
